### ISSUE TITLE
Short axis RV insertion point correction

### ISSUE THREAD

**Issue by animeshtandon** [btcrabb/CAP-Automated-Pipeline#10]
In the short axis RV insertion module (4.1), there is no widget that allows correction of the points. This functionality does exist for other localization tasks (e.g. 4CH, 3CH).

I would like a similar tool for the short axis RV insertion point localization.

Manual correction in a system outside this code is possible but not user friendly.

**Comment by btcrabb** [comment]
A tool to correct the short axis RV insertion points has been added to module 4.1. This tool is identical to the tool used for the other views (e.g., 4CH, 3CH). The relevant code is below:

```
# if necessary, update landmark predictions
from annotations import Annotate

# Settings
index = 1
slice_id = 17
landmarks_to_correct = ['RV1', 'RV2'] # should be list of labels (e.g., ['RV1', 'RV2'])

annotator = Annotate(sa_df, volume, index, slice_id, landmarks_to_correct)

%matplotlib notebook
annotator.plot()
```

```
# update dataframe and display
sa_df = annotator.update()
sa_df
```
