### ISSUE TITLE
Add patient ID

### ISSUE THREAD

**Issue by animeshtandon** [btcrabb/CAP-Automated-Pipeline#12]
In our anonymization method, the DICOM patient ID tag is removed. We wrote some code to set patient ID to the patient variable defined in the "enter user settings" code.

# set patient ID to patient variable (defined above) for all dicom files in src

for series_dir in [series_dir for series_dir in os.listdir(src) if os.path.isdir(os.path.join(src, series_dir))]:
    for dcm_file in [dcm_file for dcm_file in os.listdir(os.path.join(src, series_dir)) if dcm_file.endswith(".dcm")]:
        ds = pydicom.dcmread(os.path.join(src, series_dir, dcm_file))
        ds.PatientID = patient
        ds.save_as(os.path.join(src, series_dir, dcm_file))

**Comment by btcrabb** [comment]
Thank you for this. It is a good idea to ensure that all of the required DICOM header information is present prior to attempting to use the existing pipeline. I'll make a list of required DICOM header information and write a quick code block to check that it is all defined. If not, we can use code such as yours to add the required information.
