### ISSUE TITLE
UnboundLocalError in Guide Point Processing

### ISSUE THREAD

**Issue by animeshtandon** [btcrabb/CAP-Automated-Pipeline#13]
Hi Brendan,
I tried to go on past the segmentation stage after I thought a reasonable landmarks_df was generated. On the same linux systemn, I ran the import guidepointprocessing which yielded:

<module 'guidepointprocessing' from '/MakandaProjects/CAP-Automated-Pipeline/src/guidepointprocessing.py'>

Running the next block gives the error:

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
 in 
     13                                   landmarks_df)
     14 
---> 15 GuidePoints.extract_guidepoints(display = False)

/MakandaProjects/CAP-Automated-Pipeline/src/guidepointprocessing.py in extract_guidepoints(self, display)
    785 
    786         self.get_segmentation_files()
--> 787         self.process_short_axis(display=display)
    788         self.process_long_axis(display=display)
    789         self.process_landmarks()

/MakandaProjects/CAP-Automated-Pipeline/src/guidepointprocessing.py in process_short_axis(self, display)
    263             point_lists = [RV_endo_pts,
    264                           RV_epi_pts,
--> 265                           RV_septal_pts,
    266                           LV_epi_pts,
    267                           LV_endo_pts]

UnboundLocalError: local variable 'RV_septal_pts' referenced before assignment

--

Can't go past that to plot the guide points, when I run the next block of code:

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
 in 
      3 coordinates = []
      4 model_folder = '.[./data/processed/](https://vscode-remote+ssh-002dremote-002bmakanda.vscode-resource.vscode-cdn.net/MakandaProjects/CAP-Automated-Pipeline/notebooks/data/processed/)' + patient
----> 5 with open(model_folder + '/GP_ES.txt', 'r') as f:
      6     for i,line in enumerate(f.readlines()):
      7         if i > 0:

FileNotFoundError: [Errno 2] No such file or directory: '.[./data/processed/22-102_ccc-004r_pre/GP_ES.txt](https://vscode-remote+ssh-002dremote-002bmakanda.vscode-resource.vscode-cdn.net/MakandaProjects/CAP-Automated-Pipeline/notebooks/data/processed/22-102_ccc-004r_pre/GP_ES.txt)'

I checked the directory structure and there indeed wasn't a file GP_ES.txt.

**Comment by btcrabb** [comment]
Hi, I believe I have fixed this issue by (A) creating an empty list of septal points, in case none are found, and (B) only processing guide points for SAX slices we want in the model (this excludes apical/basal slices that were not selected during SAX slice selection). 

Updated guidepointprocessing.py, lines 201-202 to include the following check:
```
# check if slice_id is a slice/view that should be included in the final model
            if int(slice_id) in [int(x) for x in self.landmarks_df['Slice ID']]:
```
And lines 238 to 247 to include:

```
# Get intersection points between RV endo and LV epi
                if len(RV_endo_pts)>0 and len(LV_epi_pts)>0:
                    pairs = self.get_intersections(RV_endo_pts, LV_epi_pts, distance_cutoff=4.5)

                    if len(pairs) > 0:
                        RV_septal_pts = RV_endo_pts[np.unique(pairs[:,0])] # deletes intersection from RV endo pts
                        RV_endo_pts = np.array([pnt.tolist() for i, pnt in enumerate(RV_endo_pts) if i not in np.unique(pairs[:,0])], 
                                              dtype=np.int64)
                else:
                    RV_septal_pts = []
```

**Comment by btcrabb** [comment]
To update your project, replace guidepointprocessing.py with the code provided in commit d258689. Let me know if that corrects the issue you are having.
